import MobileModule from "./module/MobileModule.js";
import AosModule from "./module/AosModule.js";
import BtnToTopModule from "./module/BtnToTopModule.js";
import PopupModule from "./module/PopupModule.js";
import SelectCusModule from "./module/SelectCusModule.js";
import CheckModule from "./module/CheckModule.js";
import SearchModule from "./module/SearchModule.js";
import Select2Module from "./module/Select2Module.js";
import LetterModule from "./module/LetterModule.js";
import GalleryModule from "./module/GalleryModule.js";
import TabModule from "./module/TabModule.js";
import HeaderModule from "./module/HeaderModule.js";
import SideModule from "./module/SideModule.js";
import ShowHideModule from "./module/ShowHideModule.js";
import MenuModule from "./module/MenuModule.js";
import ScrollToSectionModule from "./module/ScrollToSectionModule.js";
import InputFile from "./module/InputFile.js";
import RangePriceModule from "./module/RangePriceModule.js";
import ChangeTypeInputModule from "./module/ChangeTypeInputModule.js";
import Amount from "./module/amount.js";
import TimerModule from "./module/timeCount.js";
import LoadMoreModule from "./module/LoadMoreModule.js";
import plyrModule from "./module/plyrModule.js";
import tooltipModule from "./module/tooltipModule.js";
import ParallaxModule from "./module/ParallaxModule.js";
import SmoothScrollModule from "./module/SmoothScrollModule.js";
import ShowPasswordModule from "./module/ShowPasswordModule.js";
import UploadFileCVModule from "./module/UploadFileCVModule.js";
import CircleText from "./module/Circletext.js";
import textCount from "./module/textCount.js";
import sliderCus from "./module/sliderCus.js";
import SwipeFun from "./module/swipe.js";
import ProductModule from "./module/ProductModule.js";
import AnimationModule from "./module/AnimationModule.min.js";
import SwiperModule from "./module/SwiperModule.js";
import Hover from "./module/Hover.js";
import LinksMain from "./module/linksMain.js";
import inputForm from "./module/input.js";


window.addEventListener("DOMContentLoaded", () => {
    HeaderModule();
    Hover();
    MenuModule();
    MobileModule();
    BtnToTopModule();
    LoadMoreModule();
    SelectCusModule();
    CheckModule();
    SearchModule();
    Select2Module();
    LetterModule();
    GalleryModule();
    TabModule();
    SwiperModule();
    PopupModule();
    AosModule();
    SideModule();
    ShowHideModule();
    AnimationModule();
    ScrollToSectionModule();
    InputFile();
    RangePriceModule();
    ChangeTypeInputModule();
    Amount();
    TimerModule();
    plyrModule();
    tooltipModule();
    ParallaxModule();
    SmoothScrollModule();
    ShowPasswordModule();
    UploadFileCVModule();
    CircleText();
    textCount();
    sliderCus();
    SwipeFun();
    ProductModule();
    LinksMain();
    inputForm();
});